### ISSUE TITLE
Markdown: Code feature (`...`)

### ISSUE THREAD

**Issue by deeptimathur1904** [sarveshraj/me#10]
## Summary
The code feature in the Markdown language is not formatting properly in the 'Let's talk about resiliency' article.
For example, "code-snippet" should be:  " `code-snippet` "

## Subtasks
- [ ] May make some changes to CSS to resolve.
- [ ] Make changes to markdown file.

## Additional information
We can add HTML tags like span with style attributes as an alternative to the "light blue" bg color of the code segments. (But markdown was not accepting the HTML styling.)

**Comment by sarveshraj** [comment]
Fixed in PR #18 

## Subtasks
- [x] May make some changes to CSS to resolve.
- [x] Make changes to markdown file: Not required
