### ISSUE TITLE
Add snackbar component

### ISSUE THREAD

**Issue by sarveshraj** [sarveshraj/me#11]
## Summary
Add support for showing snackbars at the bottom of the page, usually with call to action to share the article or let the user know that the article is available on medium.

## Subtasks
- [ ] Snackbar should be fully customizable using front matter of a post
- [ ] One post must support multiple snackbars 
- [ ] While rendering, the page should randomly show one of the snackbar on load but it should be the only one shown to user till they navigate away from the page.
- [ ] Every snackbar should have a close icon
- [ ] Some snackbars should auto dismiss. Like the one saying that the article is available on medium. Whether a snackbar will be auto dismissed must be customizable using front matter.

## Additional information
How snackbars should look and behave: https://material.io/components/snackbars/#
