### ISSUE TITLE
Support for floating, hideable index.

### ISSUE THREAD

**Issue by sarveshraj** [sarveshraj/me#12]
## Summary
Every article should have an auto-generated (using the HTML heading tags) index (table of contents).

## Subtasks
- [x] The index should be hidden by default into a persistent button on the right
- [ ] Clicking/hovering on the button should pull the index from the right side
- [x] The index should be auto-generated using the heading tags
- [x] The index should overlay the content on smaller screens
- [x] Clicking on any of the index links should take the page to the correct heading
- [x] The above action should be in the form of smooth scrolling as supported in the teams page of cepstrum's website

## Additional information
Inspiration: https://paulstamatiou.com/getting-started-with-security-keys/

**Comment by sarveshraj** [comment]
https://github.com/tscanlin/tocbot

**Comment by sarveshraj** [comment]
Hugo has inbuilt table of contents support: https://gohugo.io/content-management/toc/

**Comment by deeptimathur1904** [comment]
Completed this and added a new one. https://github.com/sarveshraj/me/issues/34
