### ISSUE TITLE
Support displaying of images of varying sizes

### ISSUE THREAD

**Issue by sarveshraj** [sarveshraj/me#13]
## Summary
Support displaying of images of varying sizes in the article pages.

## Subtasks
- [ ] Check if it is possible via markdown
- [ ] Need to support three types of images: small medium large
- [ ] Fully responsive
- [ ] Images should have inbuilt caption support
- [ ] Test by adding image(s) to first article

## Additional information
Inspiration: https://novela.narative.co/Understanding-the-Gatsby-lifecycle-with-Narative

**Comment by sarveshraj** [comment]
Consider creating shortcodes (https://gohugo.io/content-management/shortcodes/) and also look into: https://gohugo.io/content-management/image-processing/

**Comment by sarveshraj** [comment]
Fixed in #20 

## Subtasks
- [x] Check if it is possible via markdown ->  not possible, used Hugo `figure` shortcode
- [x] Need to support three types of images: small medium large -> added 4 sizes
- [x] Fully responsive
- [x] Images should have inbuilt caption support
- [x] Test by adding image(s) to first article
