### ISSUE TITLE
Medium embed on posts

### ISSUE THREAD

**Issue by sarveshraj** [sarveshraj/me#14]
## Summary
Investigate what kinds of medium embeds are available and best suited

## Subtasks
- [ ] Add medium embed support to articles
- [ ] The medium link should be passed via front matter
- [ ] Clicking on medium link should open a new tab

## Additional information
https://medium.com/datadriveninvestor/embed-medium-as-a-blog-on-your-site-54a1b49cbe16

**Comment by sarveshraj** [comment]
Fixed with #28 

## Subtasks
- [x] Add medium embed support to articles
- [x] The medium link should be passed via front matter
- [x] Clicking on the medium link should open a new tab
