### ISSUE TITLE
Tags support

### ISSUE THREAD

**Issue by sarveshraj** [sarveshraj/me#15]
## Summary
Add support to add tags to article via front matter.

## Subtasks
- [ ] Tags should be clickable.
- [ ] Tags should be able to be referenced in the article. May need to check if extended custom markdown support can be added.
- [ ] Clicking on the tag should open a page which shows all articles with that tag

## Additional information
Lot of hugo themes support this like Casper, Anake. Can take inspiration from them.

**Comment by sarveshraj** [comment]
Consider making shortcodes for tags that can be clickable within the article through the markdown. Extended custom markdown parser support is not easy.

**Comment by sarveshraj** [comment]
Read: https://blog.jeremylikness.com/blog/migrate-from-medium-to-hugo/
In general we have to use taxonomies. Consider adding a years taxonomy as well

**Comment by sarveshraj** [comment]
One more example: https://www.jakewiesler.com/blog/hugo-taxonomies/

**Comment by sarveshraj** [comment]
## Subtasks
- [x] Tags should be clickable.
- [x] Tags should be able to be referenced in the article. May need to check if extended custom markdown support can be added. -> don't need shortcodes or custom markdown, just add a link
- [x] Clicking on the tag should open a page which shows all articles with that tag
