### ISSUE TITLE
Styling issues in "let's talk .." article

### ISSUE THREAD

**Issue by deeptimathur1904** [sarveshraj/me#17]
## Summary
styling changes

## Subtasks
- [ ] Java code is properly formatted
- [ ] Java code colors are showing
- [ ] horizontal line breaks
- [ ] change the settings for italics

**Comment by sarveshraj** [comment]
Fixed in PR #18 

## Subtasks
- [x] Java code is properly formatted
- [x] Java code colors are showing
- [x] horizontal line breaks
- [x] change the settings for italics: Did not do. Changed my mind.
