### ISSUE TITLE
Add Let's talk about resiliency article 

### ISSUE THREAD

**Issue by sarveshraj** [sarveshraj/me#2]
## Summary
Add [Let's talk about resiliency](https://medium.com/@sarvesh0803/lets-talk-about-resiliency-37660be5eaf3) article as a post in the website and verify that all CSS modifications done in f0fd4e5f4e19f434c96b83e889b8b3f1463e954a look consistent.

## Checklist
- [ ] All headings and paragraphs are perfectly aligned from the left and right side
- [ ] Image looks consistent
- [ ] Code blocks work with language support
- [ ] Copy button in code blocks works and has sufficient padding
- [ ] Verified everything above for varying screen sizes
- [ ] No padding or margin on code blocks for smaller screen sizes
- [ ] Blockquotes have sufficient padding and/or margin in smaller screen sizes
- [ ] The font size for the headings adjust to varying screen sizes

**Comment by sarveshraj** [comment]
## Subtasks
- [x] All headings and paragraphs are perfectly aligned from the left and right side
- [ ] Image looks consistent - to be handled in separate issue #13 
- [x] Code blocks work with language support - handled in issue #17 
- [x] Copy button in code blocks works and has sufficient padding
- [x] Verified everything above for varying screen sizes
- [x] No padding or margin on code blocks for smaller screen sizes
- [x] Blockquotes have sufficient padding and/or margin in smaller screen sizes
- [x] The font size for the headings adjust to varying screen sizes
