### ISSUE TITLE
Enhancements in Index Support

### ISSUE THREAD

**Issue by deeptimathur1904** [sarveshraj/me#34]
## Summary
Some tweaks in the CSS for index support

## Subtasks
- [ ] The index icon should be on the right and index transition should be from the right.
- [ ] Add a different index icon using font-awesome.
- [ ] Changes in background color and text color for light and dark mode.
- [ ] The index icon should appear when the article content begins and disappear when the content ends.
- [ ] It should take up entire height in smaller screen sizes.

**Comment by sarveshraj** [comment]
Fixed in #33

## Subtasks
- [x] The index icon should be on the right and index transition should be from the right. -> transition not required
- [x] Add a different index icon using font-awesome. -> can't use font awesome as dark mode support will be difficult
- [x] Changes in background color and text color for light and dark mode.
- [x] The index icon should appear when the article content begins and disappear when the content ends.
- [x] It should take up entire height in smaller screen sizes. -> not required with new design
