### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by sarveshraj** [sarveshraj/me#39]
## Summary
Make a page about yourself, you sneaky self-centered bastard ;)

## Subtasks
- [ ] Read about yourself
- [ ] Realize you have achieved very little in life
- [ ] Start writing the first chapter about yourself
- [ ] Add that chapter to the about page

## Additional information
Ask maa and papa.
