### ISSUE TITLE
Anchored headings

### ISSUE THREAD

**Issue by sarveshraj** [sarveshraj/me#43]
## Summary
Add anchors to headings in articles for easy copy pasting, like on Github readmes or Hugo website

## Subtasks
A checklist of the expected sub-tasks which would be needed to complete this feature. Be as specific as possible.
- [ ] The deep anchor link should be available in the form of an icon 
- [ ] The icon should be a chain link
- [ ] The icon should come on the left side of heading offsetting the content
- [ ] Should change color on night mode
- [ ] Should hide away on 737 px

## Additional information
https://discourse.gohugo.io/t/adding-anchor-next-to-headers/1726/7
https://www.bryanbraun.com/anchorjs/
