### ISSUE TITLE
Remove brand icon and replace with navbar

### ISSUE THREAD

**Issue by sarveshraj** [sarveshraj/me#5]
## Summary
Remove brand icon and replace with responsive navbar which contains links to about, and blog

## Subtasks
- [ ] Remove logo
- [ ] Include a CSS framework which can has inbuilt navbar component
- [ ] Add links to the pages

## Additional information
https://minicss.org/docs#drawer
https://purecss.io/layouts/tucked-menu-vertical/

**Comment by sarveshraj** [comment]
Fixed with f2d103f7614b8da78c55b1056817de864fbc0428.

## Subtasks
- [x] Remove logo
- [ ] Include a CSS framework which has inbuilt navbar component:
Not required for now as the navbar length fits in most screen sizes
- [x] Add links to the pages
